name: develop-ci

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # develop_ci:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #   steps:
  #     - uses: ros-tooling/setup-ros@0.1.0
  #     - uses: ros-tooling/action-ros-ci@0.2.0
  #       with:
  #         package-name: turtlebot3_msgs
  #         target-ros1-distro: noetic
  #         vcs-repo-file-url: ""
  ros1-ci:
    runs-on: ubuntu-20.04
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    strategy:
      matrix:
        ros_distribution:
          - kinetic
          # - melodic
          # - noetic
        include:
          # Kinetic Kame (May 2016 - May 2021)
          - docker_image: ubuntu:16.04
            ros_distribution: kinetic
            # Setting ros_version is helpful to customize the workflow
            # depending on whether a ROS 1, or ROS 2 is being tested.
            # See 'if: ros_version ==' below for an example.
            ros_version: 1

          # # Melodic Morenia (May 2018 - May 2023)
          # - docker_image: ubuntu:bionic
          #   ros_distribution: melodic
          #   ros_version: 1

          # # Noetic Ninjemys (May 2020 - May 2025)
          # - docker_image: ubuntu:focal
          #   ros_distribution: noetic
          #   ros_version: 1
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: setup ROS environment
        uses: ros-tooling/setup-ros@0.0.20
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - name: build and test ROS1
        if: ${{ matrix.ros_version == 1 }}
        uses: ros-tooling/action-ros-ci@0.0.6
        with:
          package-name: turtlebot3_msgs
          target-ros1-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: ""